In [1]:
#Lyme Disease 
#This dataset is by county 
import pandas as pd

#1. Read CSV
df_plyme = pd.read_csv("df_plyme.csv")

In [2]:
#2. Subset update dataframe to locate only Maryland's incidence rates and create new datframe just for MD

#     #df_plyme[df_plyme['STNAME'] == 'Maryland'].index
#             #12474:72332
#             #non-consecutive
#             #552 rows total

#create new df called maryland
df_plyme_updated=df_plyme[df_plyme['STNAME'] == 'Maryland']

In [3]:
df_plyme_updated

,GEOID,STABBR,STNAME,CTYNAME,YEAR,CASES,POP,RATE
12474,24001.0,MD,Maryland,Allegany County,2001,1.0,74314.0,1.345641
12475,24001.0,MD,Maryland,Allegany County,2002,2.0,73728.0,2.712674
12476,24001.0,MD,Maryland,Allegany County,2003,2.0,73314.0,2.727992
12477,24001.0,MD,Maryland,Allegany County,2004,1.0,73379.0,1.362788
12478,24001.0,MD,Maryland,Allegany County,2005,3.0,72694.0,4.126888
...,...,...,...,...,...,...,...,...
71914,24009.0,MD,Maryland,Calvert County,2023,52.0,94728.0,54.894012
71922,24510.0,MD,Maryland,Baltimore City,2023,54.0,565239.0,9.553481
72267,24031.0,MD,Maryland,Montgomery County,2023,125.0,1058474.0,11.809454
72304,24029.0,MD,Maryland,Kent County,2023,27.0,19303.0,139.874631
72332,24025.0,MD,Maryland,Harford County,2023,147.0,264644.0,55.546319

In [4]:
#Lyme Disease 

#3. Change incidence rate so that all tickborne diseases are per 1000000 people (lyme is 100,000)
    # Need to first group by county and year
    # Then calculate totals for cases and population 
df_maryland_lyme_totals = df_plyme_updated.groupby("YEAR")[["CTYNAME", "CASES", "POP"]].sum()

In [5]:
# pd.set_option('display.max_colwidth', None)
# (df_maryland__lymetotals["CTYNAME"])

In [6]:
df_maryland_lyme_totals

                                                CTYNAME   CASES        POP
YEAR
2001  Allegany CountySt. Mary's CountyBaltimore Coun...   608.0  5375033.0
2002  Allegany CountySt. Mary's CountyBaltimore Coun...   738.0  5439913.0
2003  Allegany CountySt. Mary's CountyBaltimore Coun...   691.0  5496708.0
2004  Allegany CountySt. Mary's CountyBaltimore Coun...   891.0  5542659.0
2005  Allegany CountySt. Mary's CountyBaltimore Coun...  1235.0  5582520.0
2006  Allegany CountySt. Mary's CountyBaltimore Coun...  1247.0  5612196.0
2007  Allegany CountySt. Mary's CountyBaltimore Coun...  2561.0  5634242.0
2008  Allegany CountySt. Mary's CountyBaltimore Coun...  2218.0  5658655.0
2009  Allegany CountySt. Mary's CountyBaltimore Coun...  2021.0  5699478.0
2010  Allegany CountySt. Mary's CountyBaltimore Coun...  1617.0  5788645.0
2011  Allegany CountySt. Mary's CountyBaltimore Coun...  1350.0  5839419.0
2012  Allegany CountySt. Mary's CountyBaltimore Coun...  1648.0  5886992.0
2013  Allegany CountySt. Mary's CountyBaltimore Coun...  1197.0  5923188.0
2014  Allegany CountySt. Mary's CountyBaltimore Coun...  1372.0  5957283.0
2015  Allegany CountySt. Mary's CountyBaltimore Coun...  1728.0  5985562.0
2016  Allegany CountySt. Mary's CountyBaltimore Coun...  1866.0  6003323.0
2017  Allegany CountySt. Mary's CountyBaltimore Coun...  1888.0  6023868.0
2018  Allegany CountySt. Mary's CountyBaltimore Coun...  1382.0  6035802.0
2019  Allegany CountySt. Mary's CountyBaltimore Coun...  1417.0  6045680.0
2020  Allegany CountySt. Mary's CountyBaltimore Coun...   840.0  6173689.0
2021  Allegany CountySt. Mary's CountyBaltimore Coun...   908.0  6175045.0
2022  Allegany CountySt. Mary's CountyBaltimore Coun...  1960.0  6163981.0
2023  Allegany CountySt. Mary's CountyBaltimore Coun...  2404.0  6180253.0

In [7]:
#3. Continued
# Then need to change rate:



df_maryland_lyme_totals['ONE_MILLION_RATE'] = (df_maryland_lyme_totals["CASES"] / df_maryland_lyme_totals["POP"]) * 1000000

In [8]:
df_maryland_lyme_totals

,CTYNAME,CASES,POP,ONE_MILLION_RATE
YEAR,,,,
2001,Allegany CountySt. Mary's CountyBaltimore Coun...,608.0,5375033.0,113.115585
2002,Allegany CountySt. Mary's CountyBaltimore Coun...,738.0,5439913.0,135.663934
2003,Allegany CountySt. Mary's CountyBaltimore Coun...,691.0,5496708.0,125.711608
2004,Allegany CountySt. Mary's CountyBaltimore Coun...,891.0,5542659.0,160.753169
2005,Allegany CountySt. Mary's CountyBaltimore Coun...,1235.0,5582520.0,221.226256
2006,Allegany CountySt. Mary's CountyBaltimore Coun...,1247.0,5612196.0,222.194663
2007,Allegany CountySt. Mary's CountyBaltimore Coun...,2561.0,5634242.0,454.542066
2008,Allegany CountySt. Mary's CountyBaltimore Coun...,2218.0,5658655.0,391.965935
2009,Allegany CountySt. Mary's CountyBaltimore Coun...,2021.0,5699478.0,354.593877
2010,Allegany CountySt. Mary's CountyBaltimore Coun...,1617.0,5788645.0,279.339984
2011,Allegany CountySt. Mary's CountyBaltimore Coun...,1350.0,5839419.0,231.187384
2012,Allegany CountySt. Mary's CountyBaltimore Coun...,1648.0,5886992.0,279.939229
2013,Allegany CountySt. Mary's CountyBaltimore Coun...,1197.0,5923188.0,202.087119
2014,Allegany CountySt. Mary's CountyBaltimore Coun...,1372.0,5957283.0,230.306333
2015,Allegany CountySt. Mary's CountyBaltimore Coun...,1728.0,5985562.0,288.694696
2016,Allegany CountySt. Mary's CountyBaltimore Coun...,1866.0,6003323.0,310.827853
2017,Allegany CountySt. Mary's CountyBaltimore Coun...,1888.0,6023868.0,313.419882
2018,Allegany CountySt. Mary's CountyBaltimore Coun...,1382.0,6035802.0,228.967087
2019,Allegany CountySt. Mary's CountyBaltimore Coun...,1417.0,6045680.0,234.382237
2020,Allegany CountySt. Mary's CountyBaltimore Coun...,840.0,6173689.0,136.061276
2021,Allegany CountySt. Mary's CountyBaltimore Coun...,908.0,6175045.0,147.043463
2022,Allegany CountySt. Mary's CountyBaltimore Coun...,1960.0,6163981.0,317.976321
2023,Allegany CountySt. Mary's CountyBaltimore Coun...,2404.0,6180253.0,388.980839

In [9]:
#Lyme Disease

#4. Subset MD dataframe to extract incidence rates only from 2015-2022 (to somewhat match harvest data timeline which goes up to 2025)
df_maryland_lyme_totals=df_maryland_lyme_totals.iloc[14:]

In [10]:
#5.Save this CSV before droppping more columns 
df_maryland_lyme_totals.to_csv("df_maryland_lyme_totals.csv")

In [11]:
df_plyme_updated = df_maryland_lyme_totals.drop(["CTYNAME", "CASES", "POP"], axis = 1)

In [12]:
df_plyme_updated = df_plyme_updated.iloc[:-1]

In [13]:
#8. Add disease column for grouped bar chart 
df_plyme_updated=df_plyme_updated.assign(TICKBORNE_DISEASE = "Lyme")

#https://stackoverflow.com/questions/44657226/how-to-insert-a-new-column-with-repeated-values-into-a-pandas-table

In [14]:
df_plyme_updated['YEAR']= [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]

In [15]:
df_plyme_updated=df_plyme_updated.reset_index(drop=True)

In [16]:
df_plyme_updated.to_csv("df_plyme_updated.csv")

In [17]:
df_plyme_updated

   ONE_MILLION_RATE TICKBORNE_DISEASE  YEAR
0        288.694696              Lyme  2015
1        310.827853              Lyme  2016
2        313.419882              Lyme  2017
3        228.967087              Lyme  2018
4        234.382237              Lyme  2019
5        136.061276              Lyme  2020
6        147.043463              Lyme  2021
7        317.976321              Lyme  2022