In [1]:

import pandas as pd

df_analysis_lyme = pd.read_csv("df_plyme.csv")
df_analysis_lyme.columns

Index(['GEOID', 'STABBR', 'STNAME', 'CTYNAME', 'YEAR', 'CASES', 'POP', 'RATE'], dtype='str')

In [2]:
##------Next several cells calculate national incidence rates per year from 2015-2022 for each tickborne disease to compare it to Maryland-----##

#NOTE: I MESSED UP THE VARIABLE NAMEs. THESE ARE NOT AVERAGES!!

In [3]:
#Lyme national average incidence rates from 2015 to 2022
df_analysis_lyme.query("YEAR >= 2015 and YEAR <= 2022")

         GEOID STABBR STNAME          CTYNAME  YEAR  CASES      POP      RATE
14     39071.0     OH   Ohio  Highland County  2015    0.0  42960.0  0.000000
15     39071.0     OH   Ohio  Highland County  2016    0.0  43006.0  0.000000
16     39071.0     OH   Ohio  Highland County  2017    0.0  42903.0  0.000000
17     39071.0     OH   Ohio  Highland County  2018    0.0  43052.0  0.000000
18     39071.0     OH   Ohio  Highland County  2019    1.0  43161.0  2.316906
...        ...    ...    ...              ...   ...    ...      ...       ...
69317      NaN    NaN    NaN              NaN  2018    NaN      NaN       NaN
69318      NaN    NaN    NaN              NaN  2019    NaN      NaN       NaN
69319      NaN    NaN    NaN              NaN  2020    NaN      NaN       NaN
69320      NaN    NaN    NaN              NaN  2021    NaN      NaN       NaN
69321      NaN    NaN    NaN              NaN  2022    NaN      NaN       NaN

[25208 rows x 8 columns]

In [4]:
lyme_cases_15 = df_analysis_lyme.query("YEAR == 2015")

In [5]:
cases_sum_15=lyme_cases_15["CASES"].sum ()

In [6]:
pop_sum_15=lyme_cases_15["POP"].sum()

In [7]:
lyme_avg_15 = (cases_sum_15/pop_sum_15)*1000000

In [8]:
lyme_avg_15

np.float64(117.21421832950992)

In [9]:
lyme_cases_16 = df_analysis_lyme.query("YEAR == 2016")

In [10]:
cases_sum_16=lyme_cases_16["CASES"].sum ()

In [11]:
pop_sum_16=lyme_cases_16["POP"].sum()

In [12]:
lyme_avg_16 = (cases_sum_16/pop_sum_16)*1000000

In [13]:
lyme_avg_16

np.float64(111.4939426253831)

In [14]:
lyme_cases_17 = df_analysis_lyme.query("YEAR == 2017")
cases_sum_17=lyme_cases_17["CASES"].sum ()
pop_sum_17=lyme_cases_17["POP"].sum()
lyme_avg_17 = (cases_sum_17/pop_sum_17)*1000000
lyme_avg_17

np.float64(130.2242559168148)

In [15]:
lyme_cases_18 = df_analysis_lyme.query("YEAR == 2018")
cases_sum_18=lyme_cases_18["CASES"].sum ()
pop_sum_18=lyme_cases_18["POP"].sum()
lyme_avg_18 = (cases_sum_18/pop_sum_18)*1000000
lyme_avg_18

np.float64(102.11593617106276)

In [16]:
lyme_cases_19 = df_analysis_lyme.query("YEAR == 2019")
cases_sum_19=lyme_cases_19["CASES"].sum ()
pop_sum_19=lyme_cases_19["POP"].sum()
lyme_avg_19 = (cases_sum_19/pop_sum_19)*1000000
lyme_avg_19

np.float64(104.23790434279908)

In [17]:
lyme_cases_20 = df_analysis_lyme.query("YEAR == 2020")
cases_sum_20=lyme_cases_20["CASES"].sum ()
pop_sum_20=lyme_cases_20["POP"].sum()
lyme_avg_20 = (cases_sum_20/pop_sum_20)*1000000
lyme_avg_20

np.float64(53.708116017566454)

In [18]:
lyme_cases_21 = df_analysis_lyme.query("YEAR == 2021")
cases_sum_21=lyme_cases_21["CASES"].sum ()
pop_sum_21=lyme_cases_21["POP"].sum()
lyme_avg_21 = (cases_sum_21/pop_sum_21)*1000000
lyme_avg_21

np.float64(73.44051853975816)

In [19]:
lyme_cases_22 = df_analysis_lyme.query("YEAR == 2022")
cases_sum_22=lyme_cases_22["CASES"].sum ()
pop_sum_22=lyme_cases_22["POP"].sum()
lyme_avg_22 = (cases_sum_22/pop_sum_22)*1000000
lyme_avg_22

np.float64(185.4797863344404)

In [20]:
#Lyme disease incidence rates from this .csv match with "df_plyme_updated.csv" that was created when looking at incidence rate in Maryland per year, with all counties lumped together
#This is a horrible dataframe name because it includes more than just Lyme. But I'm afraid to change it now because I don't know where else I used it. Sorry!

lyme_md_nat_compare = pd.read_csv("df_md_tickborne_incidence.csv")

In [21]:
lyme_md_nat_compare

,YEAR,Anaplasmosis,Babesiosis,Ehrlichiosis,Lyme,Spotted Fever Rickettsiosis
0,2015,0.313798,0.668275,5.012061,288.694696,0.668275
1,2016,0.547013,0.999446,5.996679,310.827853,0.166574
2,2017,0.623029,0.830031,7.802296,313.419882,10.126384
3,2018,0.699439,1.159746,12.591533,228.967087,17.561875
4,2019,1.241994,1.157852,11.082293,234.382237,22.660809
5,2020,0.465292,1.457799,8.746796,136.061276,3.239554
6,2021,1.629866,2.105248,10.850123,147.043463,2.267190
7,2022,1.710876,1.135630,11.194064,317.976321,2.595725

In [22]:
nat_averages_15_22 = [117.21,111.49,130.22, 102.12, 104.24, 53.71, 73.44, 185.48]
lyme_md_nat_compare['Lyme_National_Rate'] = nat_averages_15_22

In [23]:
lyme_md_nat_compare = lyme_md_nat_compare[['YEAR', 'Anaplasmosis', 'Babesiosis', 'Ehrlichiosis', 'Spotted Fever Rickettsiosis',
                                          'Lyme', 'Lyme_National_Rate']]

In [24]:
lyme_md_nat_compare

,YEAR,Anaplasmosis,Babesiosis,Ehrlichiosis,Spotted Fever Rickettsiosis,Lyme,Lyme_National_Rate
0,2015,0.313798,0.668275,5.012061,0.668275,288.694696,117.21
1,2016,0.547013,0.999446,5.996679,0.166574,310.827853,111.49
2,2017,0.623029,0.830031,7.802296,10.126384,313.419882,130.22
3,2018,0.699439,1.159746,12.591533,17.561875,228.967087,102.12
4,2019,1.241994,1.157852,11.082293,22.660809,234.382237,104.24
5,2020,0.465292,1.457799,8.746796,3.239554,136.061276,53.71
6,2021,1.629866,2.105248,10.850123,2.267190,147.043463,73.44
7,2022,1.710876,1.135630,11.194064,2.595725,317.976321,185.48

In [25]:
lyme_md_nat_compare.to_csv("lyme_md_nat_compare.csv")

In [26]:
df_analysis_ana = pd.read_csv("df_pana.csv")

In [27]:
ana_cases_15 = df_analysis_ana.query("YEAR == 2015")
ana_cases_sum_15=ana_cases_15["CASES_A"].sum ()
ana_pop_sum_15=ana_cases_15["POP"].sum()
ana_avg_15 = (ana_cases_sum_15/ana_pop_sum_15)*1000000
ana_avg_15

np.float64(11.402367618675685)

In [28]:
ana_cases_16 = df_analysis_ana.query("YEAR == 2016")
ana_cases_sum_16=ana_cases_16["CASES_A"].sum ()
ana_pop_sum_16=ana_cases_16["POP"].sum()
ana_avg_16 = (ana_cases_sum_16/ana_pop_sum_16)*1000000
ana_avg_16

np.float64(12.853728707381139)

In [29]:
ana_cases_17 = df_analysis_ana.query("YEAR == 2017")
ana_cases_sum_17=ana_cases_17["CASES_A"].sum ()
ana_pop_sum_17=ana_cases_17["POP"].sum()
ana_avg_17 = (ana_cases_sum_17/ana_pop_sum_17)*1000000
ana_avg_17

np.float64(10.332767452769644)

In [30]:
ana_cases_18 = df_analysis_ana.query("YEAR == 2018")
ana_cases_sum_18=ana_cases_18["CASES_A"].sum ()
ana_pop_sum_18=ana_cases_18["POP"].sum()
ana_avg_18 = (ana_cases_sum_18/ana_pop_sum_18)*1000000
ana_avg_18

np.float64(12.268605280983799)

In [31]:
ana_cases_19 = df_analysis_ana.query("YEAR == 2019")
ana_cases_sum_19=ana_cases_19["CASES_A"].sum ()
ana_pop_sum_19=ana_cases_19["POP"].sum()
ana_avg_19 = (ana_cases_sum_19/ana_pop_sum_19)*1000000
ana_avg_19

np.float64(17.22827265990147)

In [32]:
ana_cases_20 = df_analysis_ana.query("YEAR == 2020")
ana_cases_sum_20=ana_cases_20["CASES_A"].sum ()
ana_pop_sum_20=ana_cases_20["POP"].sum()
ana_avg_20 = (ana_cases_sum_20/ana_pop_sum_20)*1000000
ana_avg_20

np.float64(10.970451079460263)

In [33]:
ana_cases_21 = df_analysis_ana.query("YEAR == 2021")
ana_cases_sum_21=ana_cases_21["CASES_A"].sum ()
ana_pop_sum_21=ana_cases_21["POP"].sum()
ana_avg_21 = (ana_cases_sum_21/ana_pop_sum_21)*1000000
ana_avg_21

np.float64(20.265082762173364)

In [34]:
ana_cases_22 = df_analysis_ana.query("YEAR == 2022")
ana_cases_sum_22=ana_cases_22["CASES_A"].sum ()
ana_pop_sum_22=ana_cases_22["POP"].sum()
ana_avg_22 = (ana_cases_sum_22/ana_pop_sum_22)*1000000
ana_avg_22

np.float64(16.95614989309719)

In [35]:
nat_ana_averages_15_22 = [11.40,12.85,10.33,12.27,17.23,10.97,20.27, 16.96]
lyme_md_nat_compare['Anaplasmosis_National_Rate'] = nat_ana_averages_15_22

In [36]:
lyme_md_nat_compare=lyme_md_nat_compare[['YEAR', 'Anaplasmosis', "Anaplasmosis_National_Rate",'Babesiosis', 'Ehrlichiosis', 'Spotted Fever Rickettsiosis',
                                          'Lyme', 'Lyme_National_Rate']]

In [37]:
lyme_md_nat_compare

,YEAR,Anaplasmosis,Anaplasmosis_National_Rate,Babesiosis,Ehrlichiosis,Spotted Fever Rickettsiosis,Lyme,Lyme_National_Rate
0,2015,0.313798,11.40,0.668275,5.012061,0.668275,288.694696,117.21
1,2016,0.547013,12.85,0.999446,5.996679,0.166574,310.827853,111.49
2,2017,0.623029,10.33,0.830031,7.802296,10.126384,313.419882,130.22
3,2018,0.699439,12.27,1.159746,12.591533,17.561875,228.967087,102.12
4,2019,1.241994,17.23,1.157852,11.082293,22.660809,234.382237,104.24
5,2020,0.465292,10.97,1.457799,8.746796,3.239554,136.061276,53.71
6,2021,1.629866,20.27,2.105248,10.850123,2.267190,147.043463,73.44
7,2022,1.710876,16.96,1.135630,11.194064,2.595725,317.976321,185.48

In [38]:
lyme_md_nat_compare.to_csv("lyme_md_nat_compare.csv")

In [39]:
df_analysis_ehr = pd.read_csv("df_pehr.csv")

In [40]:
ehr_cases_15 = df_analysis_ehr.query("YEAR == 2015")
ehr_cases_sum_15=ehr_cases_15["CASES_EC"].sum ()
ehr_pop_sum_15=ehr_cases_15["POP"].sum()
ehr_avg_15 = (ehr_cases_sum_15/ehr_pop_sum_15)*1000000
ehr_avg_15

np.float64(4.017026666535635)

In [41]:
ehr_cases_16 = df_analysis_ehr.query("YEAR == 2016")
ehr_cases_sum_16=ehr_cases_16["CASES_EC"].sum ()
ehr_pop_sum_16=ehr_cases_16["POP"].sum()
ehr_avg_16 = (ehr_cases_sum_16/ehr_pop_sum_16)*1000000
ehr_avg_16

np.float64(4.263932649979241)

In [42]:
ehr_cases_17 = df_analysis_ehr.query("YEAR == 2017")
ehr_cases_sum_17=ehr_cases_17["CASES_EC"].sum ()
ehr_pop_sum_17=ehr_cases_17["POP"].sum()
ehr_avg_17 = (ehr_cases_sum_17/ehr_pop_sum_17)*1000000
ehr_avg_17

np.float64(5.052532506684859)

In [43]:
ehr_cases_18 = df_analysis_ehr.query("YEAR == 2018")
ehr_cases_sum_18=ehr_cases_18["CASES_EC"].sum ()
ehr_pop_sum_18=ehr_cases_18["POP"].sum()
ehr_avg_18 = (ehr_cases_sum_18/ehr_pop_sum_18)*1000000
ehr_avg_18

np.float64(5.506791641838786)

In [44]:
ehr_cases_19 = df_analysis_ehr.query("YEAR == 2019")
ehr_cases_sum_19=ehr_cases_19["CASES_EC"].sum ()
ehr_pop_sum_19=ehr_cases_19["POP"].sum()
ehr_avg_19 = (ehr_cases_sum_19/ehr_pop_sum_19)*1000000
ehr_avg_19

np.float64(6.376441145388821)

In [45]:
ehr_cases_20 = df_analysis_ehr.query("YEAR == 2020")
ehr_cases_sum_20=ehr_cases_20["CASES_EC"].sum ()
ehr_pop_sum_20=ehr_cases_20["POP"].sum()
ehr_avg_20 = (ehr_cases_sum_20/ehr_pop_sum_20)*1000000
ehr_avg_20

np.float64(3.5532558074248524)

In [46]:
ehr_cases_21 = df_analysis_ehr.query("YEAR == 2021")
ehr_cases_sum_21=ehr_cases_21["CASES_EC"].sum ()
ehr_pop_sum_21=ehr_cases_21["POP"].sum()
ehr_avg_21 = (ehr_cases_sum_21/ehr_pop_sum_21)*1000000
ehr_avg_21

np.float64(4.026514437958952)

In [47]:
ehr_cases_22 = df_analysis_ehr.query("YEAR == 2022")
ehr_cases_sum_22=ehr_cases_22["CASES_EC"].sum ()
ehr_pop_sum_22=ehr_cases_22["POP"].sum()
ehr_avg_22 = (ehr_cases_sum_22/ehr_pop_sum_22)*1000000
ehr_avg_22

np.float64(4.707874567734824)

In [48]:
nat_ehr_averages_15_22 = [4.02,4.26,5.05,5.51,6.38,3.55,4.03, 4.71]
lyme_md_nat_compare['Ehrlichiosis_National_Rate'] = nat_ehr_averages_15_22

In [49]:
lyme_md_nat_compare=lyme_md_nat_compare[['YEAR', 'Anaplasmosis', "Anaplasmosis_National_Rate",'Babesiosis', 'Ehrlichiosis', 'Ehrlichiosis_National_Rate', 'Spotted Fever Rickettsiosis',
                                          'Lyme', 'Lyme_National_Rate']]

In [50]:
lyme_md_nat_compare.to_csv("lyme_md_nat_compare.csv")

In [51]:
df_analysis_bab = pd.read_csv("df_pbabesiosis.csv")

In [52]:
df_analysis_bab.columns

Index(['STATEFP', 'STUSPS', 'NAME', 'YEAR', 'CASES', 'POP', 'RATE'], dtype='str')

In [53]:
bab_cases_15 = df_analysis_bab.query("YEAR == 2015")
bab_cases_sum_15=bab_cases_15["CASES"].sum ()
bab_pop_sum_15=bab_cases_15["POP"].sum()
bab_avg_15 = (bab_cases_sum_15/bab_pop_sum_15)*1000000
bab_avg_15

np.float64(6.468410952169959)

In [54]:
bab_cases_16 = df_analysis_bab.query("YEAR == 2016")
bab_cases_sum_16=bab_cases_16["CASES"].sum ()
bab_pop_sum_16=bab_cases_16["POP"].sum()
bab_avg_16 = (bab_cases_sum_16/bab_pop_sum_16)*1000000
bab_avg_16

np.float64(5.734788139260387)

In [55]:
bab_cases_17 = df_analysis_bab.query("YEAR == 2017")
bab_cases_sum_17=bab_cases_17["CASES"].sum ()
bab_pop_sum_17=bab_cases_17["POP"].sum()
bab_avg_17 = (bab_cases_sum_17/bab_pop_sum_17)*1000000
bab_avg_17

np.float64(7.255707460878743)

In [56]:
bab_cases_18 = df_analysis_bab.query("YEAR == 2018")
bab_cases_sum_18=bab_cases_18["CASES"].sum ()
bab_pop_sum_18=bab_cases_18["POP"].sum()
bab_avg_18 = (bab_cases_sum_18/bab_pop_sum_18)*1000000
bab_avg_18

np.float64(6.614884234582333)

In [57]:
bab_cases_19 = df_analysis_bab.query("YEAR == 2019")
bab_cases_sum_19=bab_cases_19["CASES"].sum ()
bab_pop_sum_19=bab_cases_19["POP"].sum()
bab_avg_19 = (bab_cases_sum_19/bab_pop_sum_19)*1000000
bab_avg_19

np.float64(7.372664869489223)

In [58]:
bab_cases_20 = df_analysis_bab.query("YEAR == 2020")
bab_cases_sum_20=bab_cases_20["CASES"].sum ()
bab_pop_sum_20=bab_cases_20["POP"].sum()
bab_avg_20 = (bab_cases_sum_20/bab_pop_sum_20)*1000000
bab_avg_20

np.float64(5.489750059009535)

In [59]:
bab_cases_21 = df_analysis_bab.query("YEAR == 2021")
bab_cases_sum_21=bab_cases_21["CASES"].sum ()
bab_pop_sum_21=bab_cases_21["POP"].sum()
bab_avg_21 = (bab_cases_sum_21/bab_pop_sum_21)*1000000
bab_avg_21

np.float64(8.053028875917905)

In [60]:
bab_cases_22 = df_analysis_bab.query("YEAR == 2022")
bab_cases_sum_22=bab_cases_22["CASES"].sum ()
bab_pop_sum_22=bab_cases_22["POP"].sum()
bab_avg_22 = (bab_cases_sum_22/bab_pop_sum_22)*1000000
bab_avg_22

np.float64(6.334176680999499)

In [61]:
nat_bab_averages_15_22 = [6.47,5.73,7.26,6.61,7.37,5.49,8.05,6.33]
lyme_md_nat_compare['Babesiosis_National_Rate'] = nat_bab_averages_15_22

In [62]:
lyme_md_nat_compare=lyme_md_nat_compare[['YEAR', 'Anaplasmosis', "Anaplasmosis_National_Rate",'Babesiosis', 'Babesiosis_National_Rate','Ehrlichiosis', 'Ehrlichiosis_National_Rate', 'Spotted Fever Rickettsiosis',
                                          'Lyme', 'Lyme_National_Rate']]

In [63]:
lyme_md_nat_compare.to_csv("lyme_md_nat_compare.csv")

In [64]:
df_analysis_sfr = pd.read_csv("df_psfr.csv")

In [65]:
df_analysis_sfr.columns

Index(['STATEFP', 'STUSPS', 'NAME', 'YEAR', 'CASES', 'POP', 'RATE'], dtype='str')

In [66]:
sfr_cases_15 = df_analysis_sfr.query("YEAR == 2015")
sfr_cases_sum_15=sfr_cases_15["CASES"].sum ()
sfr_pop_sum_15=sfr_cases_15["POP"].sum()
sfr_avg_15 = (sfr_cases_sum_15/sfr_pop_sum_15)*1000000
sfr_avg_15

np.float64(13.092762380525306)

In [67]:
sfr_cases_16 = df_analysis_sfr.query("YEAR == 2016")
sfr_cases_sum_16=sfr_cases_16["CASES"].sum ()
sfr_pop_sum_16=sfr_cases_16["POP"].sum()
sfr_avg_16 = (sfr_cases_sum_16/sfr_pop_sum_16)*1000000
sfr_avg_16

np.float64(13.219120176297295)

In [68]:
sfr_cases_17 = df_analysis_sfr.query("YEAR == 2017")
sfr_cases_sum_17=sfr_cases_17["CASES"].sum ()
sfr_pop_sum_17=sfr_cases_17["POP"].sum()
sfr_avg_17 = (sfr_cases_sum_17/sfr_pop_sum_17)*1000000
sfr_avg_17

np.float64(19.22547082933435)

In [69]:
sfr_cases_18 = df_analysis_sfr.query("YEAR == 2018")
sfr_cases_sum_18=sfr_cases_18["CASES"].sum ()
sfr_pop_sum_18=sfr_cases_18["POP"].sum()
sfr_avg_18 = (sfr_cases_sum_18/sfr_pop_sum_18)*1000000
sfr_avg_18

np.float64(16.970346226989566)

In [70]:
sfr_cases_19 = df_analysis_sfr.query("YEAR == 2019")
sfr_cases_sum_19=sfr_cases_19["CASES"].sum ()
sfr_pop_sum_19=sfr_cases_19["POP"].sum()
sfr_avg_19 = (sfr_cases_sum_19/sfr_pop_sum_19)*1000000
sfr_avg_19

np.float64(15.863415692326607)

In [71]:
sfr_cases_20 = df_analysis_sfr.query("YEAR == 2020")
sfr_cases_sum_20=sfr_cases_20["CASES"].sum ()
sfr_pop_sum_20=sfr_cases_20["POP"].sum()
sfr_avg_20 = (sfr_cases_sum_20/sfr_pop_sum_20)*1000000
sfr_avg_20

np.float64(3.544206768866046)

In [72]:
sfr_cases_21 = df_analysis_sfr.query("YEAR == 2021")
sfr_cases_sum_21=sfr_cases_21["CASES"].sum ()
sfr_pop_sum_21=sfr_cases_21["POP"].sum()
sfr_avg_21 = (sfr_cases_sum_21/sfr_pop_sum_21)*1000000
sfr_avg_21

np.float64(3.785586124543308)

In [73]:
sfr_cases_22 = df_analysis_sfr.query("YEAR == 2022")
sfr_cases_sum_22=sfr_cases_22["CASES"].sum ()
sfr_pop_sum_22=sfr_cases_22["POP"].sum()
sfr_avg_22 = (sfr_cases_sum_22/sfr_pop_sum_22)*1000000
sfr_avg_22

np.float64(3.8767201666752023)

In [74]:
nat_sfr_averages_15_22 = [13.09, 13.22,19.23,16.97,15.86,3.54,3.79,3.88]
lyme_md_nat_compare['Spotted_Fever_Rickettsiosis_National_Rate'] = nat_sfr_averages_15_22

In [75]:
lyme_md_nat_compare=lyme_md_nat_compare[['YEAR', 'Anaplasmosis', "Anaplasmosis_National_Rate",'Babesiosis', 'Babesiosis_National_Rate','Ehrlichiosis', 'Ehrlichiosis_National_Rate', 'Spotted Fever Rickettsiosis', 'Spotted_Fever_Rickettsiosis_National_Rate',
                                          'Lyme', 'Lyme_National_Rate']]

In [76]:
lyme_md_nat_compare

,YEAR,Anaplasmosis,Anaplasmosis_National_Rate,Babesiosis,Babesiosis_National_Rate,Ehrlichiosis,Ehrlichiosis_National_Rate,Spotted Fever Rickettsiosis,Spotted_Fever_Rickettsiosis_National_Rate,Lyme,Lyme_National_Rate
0,2015,0.313798,11.40,0.668275,6.47,5.012061,4.02,0.668275,13.09,288.694696,117.21
1,2016,0.547013,12.85,0.999446,5.73,5.996679,4.26,0.166574,13.22,310.827853,111.49
2,2017,0.623029,10.33,0.830031,7.26,7.802296,5.05,10.126384,19.23,313.419882,130.22
3,2018,0.699439,12.27,1.159746,6.61,12.591533,5.51,17.561875,16.97,228.967087,102.12
4,2019,1.241994,17.23,1.157852,7.37,11.082293,6.38,22.660809,15.86,234.382237,104.24
5,2020,0.465292,10.97,1.457799,5.49,8.746796,3.55,3.239554,3.54,136.061276,53.71
6,2021,1.629866,20.27,2.105248,8.05,10.850123,4.03,2.267190,3.79,147.043463,73.44
7,2022,1.710876,16.96,1.135630,6.33,11.194064,4.71,2.595725,3.88,317.976321,185.48

In [124]:
lyme_md_nat_compare.to_csv("lyme_md_nat_compare.csv")